### JSF CONFIGS ###
server:
  context_parameters:
    com:
      sun:
        faces:
          forceLoadConfiguration: true


### H2 ###"
spring:
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
