### JSF CONFIGS ###
server:
  context_parameters:
    com:
      sun:
        faces:
          forceLoadConfiguration: true


### H2 ###"
spring:
  datasource:
    url: jdbc:h2:file:~/persistent;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  h2:
    console.enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace